# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultiScrollView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MultiScrollView
  pod 'SnapKit'
  pod 'JXCategoryView'
  pod 'MJRefresh'

  target 'MultiScrollViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultiScrollViewUITests' do
    # Pods for testing
  end

end
